2020-05-09 18:47:49,744 INFO: Microblog startup [in /home/ubuntu/git-tasks/microblog/app/__init__.py:47]
2020-05-09 18:47:50,770 INFO: Microblog startup [in /home/ubuntu/git-tasks/microblog/app/__init__.py:47]
2020-05-09 18:48:02,858 ERROR: Exception on /edit_profile [GET] [in /usr/local/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ubuntu/git-tasks/microblog/app/routes.py", line 87, in edit_profile
    form = EditProfileForm()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2020-05-09 18:48:19,158 ERROR: Exception on /edit_profile [GET] [in /usr/local/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ubuntu/git-tasks/microblog/app/routes.py", line 87, in edit_profile
    form = EditProfileForm()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2020-05-09 18:50:23,995 INFO: Microblog startup [in /home/ubuntu/git-tasks/microblog/app/__init__.py:47]
2020-05-09 18:51:02,142 INFO: Microblog startup [in /home/ubuntu/git-tasks/microblog/app/__init__.py:47]
2020-05-09 18:53:52,794 INFO: Microblog startup [in /home/ubuntu/git-tasks/microblog/app/__init__.py:47]
